### ISSUE TITLE
Sử dụng remark lint để chất lượng file markdown tạo ra tốt nhất

### ISSUE THREAD

**Issue by thangngoc89** [daynhauhoc/cppcoban#1]
Bằng việc dùng https://github.com/wooorm/remark-lint . Chúng ta sẽ buộc người viết đạt phải viết đúng chuẩn Common Mark. Có thể đem render ở bất kì đâu sử dụng chuẩn này mà vẫn đảm bảo là không thay đổi cách hiển thị

**Comment by trandatnh** [comment]
Cái này thêm vào thế nào? Em có thể giúp để thêm cái nào vào project mình không?

**Comment by thangngoc89** [comment]
Cái này em đang áp dụng cho blog của em.

2 cách: 

- Manual: Yêu cầu phải có node js runtime. Trước khi commit/push thì chạy lệnh `npm run lint`. Nhưng mà kiểu này thì nếu không có nodejs cũng lười làm lắm. Có thể tự động hóa trước khi commit nhưng vẫn yêu cầu node.

- Auto: Dùng Travis CI. Tự động hoàn toàn mỗi khi code được push lên repo/ hay trong mỗi PR. 

Nếu anh đồng ý dùng remark-lint thì em sẽ setup cả 2.

**Comment by trandatnh** [comment]
OK, quá muốn đi chứ :)
