### ISSUE TITLE
Dùng slug cho tên file thay vì camelCase

### ISSUE THREAD

**Issue by thangngoc89** [daynhauhoc/cppcoban#7]
Vì mục tiêu của mình là các file trên đây có thể đọc dễ dàng trên Github cũng như là website nên Khoa đề nghị là mình sẽ đặt tên file dạng slug. (nguyên tắc chung của url).

Ví dụ: `0.gioiThieuTongQuan -> 0-gioi-thieu-tong-quan`

poke @trandatnh

**Comment by trandatnh** [comment]
I'm OK with that :+1:

2016-04-16 13:10 GMT+08:00 Khoa Nguyen <notifications@github.com>:

**Comment by thangngoc89** [comment]
PR's comming

**Comment by trandatnh** [comment]
Great :dancer:
